/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package name;

import static java.lang.Character.getNumericValue;

/**
 *
 * @author Ghidorah
 */
public class NameBox extends javax.swing.JFrame {

    /**
     * Creates new form NameBox
     */
    String[] firstNames =
    {
        "Electoral College",
        "Harambe",
        "Dat Boi",
        "Clickbait",
        "Angry Arthur",
        "Confused Mr. Krabs",
        "Donald Trump",
        "Bee Movie",
        "Evil Kermit",
        "Joe Biden",
        "Obama",
        "Hillary",
        "Pokemon GO",
        "Pepe",
        "Bernie Sanders",
        "Ken Bone",
        "Hillary E-Mail",
        "Ted Cruz",
        "SpongeGar",
        "the guys she tells you not to worry about",
        "Putin",
        "Zika Virus",
    };
    
    String[] lastNames =
    {
        "performed a bottle flip",
        "did #MannequinChallege",
        "created a Hamilton Parody",
        "voted for #Brexit",
        "was a Bernie or Hillary issue",
        "is the Zodiac Killer",
        "hacked the DNC",
        "was crushed on the Hydraulic Press Channel",
        "went into a transgender bathroom",
        "was mention in the Panama Papers",
        "performed a nuclear test",
        "fell victim to a creep clown",
        "was the victim of a DDOS attack",
        "went Live on Facebook",
        "fell into a gorilla enclosure"
    };
    
    public NameBox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        nameLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        generateButton = new javax.swing.JButton();
        resultLabel = new javax.swing.JLabel();
        resultLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Name Generator");

        nameLabel.setFont(new java.awt.Font("HelvLight", 1, 12)); // NOI18N
        nameLabel.setText("Name");

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        generateButton.setFont(new java.awt.Font("HelvLight", 1, 12)); // NOI18N
        generateButton.setText("Generate");
        generateButton.setToolTipText("Do it... Push the button...");
        generateButton.setAutoscrolls(true);
        generateButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        generateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(216, 216, 216)
                                .addComponent(nameLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(202, 202, 202)
                                .addComponent(generateButton)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(resultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 102, Short.MAX_VALUE)
                .addComponent(resultLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generateButton)
                .addGap(29, 29, 29)
                .addComponent(resultLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultLabel)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButtonActionPerformed
        //get text from input field
        String name = nameField.getText();
        //if input was empty set message t0 ask for text  
        if(name.length()==0){
            resultLabel.setText("You didn't type anything..."); 
            return;
        }
        //define variables for space, first name and random last name
        char space = ' ';
        int f = getNumericValue(name.charAt(0));
        int l = (int)(Math.random()*17);
        //determine if text contains one or two names. If 2, assign variable for last name
        if(name.indexOf(space) != -1){
            try{
                l = getNumericValue(name.charAt(name.indexOf(space)+1));
            }catch(Exception e){

            }
        }
        //set messages by using character values as array indexes for circular array
        resultLabel2.setText("You were sent over the edge in 2016 because");
        resultLabel.setText(firstNames[(f+1)%23] + " " + lastNames[(l+1)%15]+".");
    }//GEN-LAST:event_generateButtonActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NameBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NameBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NameBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NameBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NameBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton generateButton;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JLabel resultLabel2;
    // End of variables declaration//GEN-END:variables
}
